<?php
/**
 * Fontis eWAY Australia Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Fontis
 * @package    Fontis_EwayAu
 * @author     Chris Norton
 * @author     Matthew Gamble
 * @author     Ron Carr
 * @copyright  Copyright (c) 2014 Fontis Pty. Ltd. (http://www.fontis.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php
$code = $this->getMethodCode();
/** @var $paymentHelper Mage_Payment_Helper_Data */
$paymentHelper = Mage::helper('payment');
?>

<script type="text/javascript">
Validation.creditCartTypes.JCB = [new RegExp('^(35[0-9]{14}|(2131|1800)[0-9]{11})$'), new RegExp('^([0-9]{3})?$'), true];
Validation.creditCartTypes.DICL = [new RegExp('^((300|305)[0-9]{11}|36[0-9]{12}|55[0-9]{14})$'), new RegExp('^([0-9]{3})?$'), false];
</script>

<ul id="payment_form_<?php echo $code; ?>" style="display:none">
    <li>
        <div class="input-box">
            <label for="<?php echo $code ?>_cc_owner"><?php echo $paymentHelper->__('Name on Card'); ?> <span class="required">*</span></label>
            <br/>
            <input type="text" title="<?php echo $paymentHelper->__('Name on Card'); ?>" class="required-entry input-text" id="<?php echo $code; ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->getInfoData('cc_owner'); ?>"/>
        </div>
    </li>
    <li>
        <div class="input-box">
            <label for="<?php echo $code; ?>_cc_type"><?php echo $paymentHelper->__('Credit Card Type'); ?> <span class="required">*</span></label>
            <br/>
            <select id="<?php echo $code; ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
            <?php $ccType = $this->getInfoData('cc_type') ?>
                <option value=""></option>
            <?php foreach ($this->getCcAvailableTypes() as $typeCode => $typeName): ?>
                <option value="<?php echo $typeCode; ?>" <?php if ($typeCode == $ccType): ?>selected="selected"<?php endif; ?>><?php echo $typeName; ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <li>
        <div class="input-box">
            <label for="<?php echo $code ?>_cc_number"><?php echo $paymentHelper->__('Credit Card Number'); ?> <span class="required">*</span></label>
            <br/>
            <input type="text" id="<?php echo $code; ?>_cc_number" name="payment[cc_number]" title="<?php echo $paymentHelper->__('Credit Card Number'); ?>" class="input-text validate-cc-number" value="<?php echo $this->getInfoData('cc_number'); ?>"/>
        </div>
    </li>
    <li>
        <div class="input-box">
            <label for="<?php echo $code; ?>_expiration"><?php echo $paymentHelper->__('Expiration Date'); ?> <span class="required">*</span></label>
            <br/>
            <select id="<?php echo $code; ?>_expiration" style="width:140px;" name="payment[cc_exp_month]" class="required-entry">
            <?php $ccExpMonth = $this->getInfoData('cc_exp_month'); ?>
            <?php foreach ($this->getCcMonths() as $k => $v): ?>
                <option value="<?php echo $k; ?>" <?php if ($k == $ccExpMonth): ?>selected="selected"<?php endif; ?>><?php echo $v; ?></option>
            <?php endforeach ?>
            </select>

            <?php $ccExpYear = $this->getInfoData('cc_exp_year'); ?>
            <select id="<?php echo $code; ?>_expiration_yr" style="width:103px;" name="payment[cc_exp_year]" class="required-entry">
            <?php foreach ($this->getCcYears() as $k => $v): ?>
                <option value="<?php echo $k ? $k : '' ?>" <?php if ($k == $ccExpYear): ?>selected="selected"<?php endif; ?>><?php echo $v; ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <?php if($this->hasVerification()): ?>
    <li>
        <div class="input-box">
            <label for="<?php echo $code ?>_cc_cid"><?php echo $paymentHelper->__('Card Verification Number'); ?> <span class="required">*</span></label><br/>
            <input type="text" title="<?php echo $paymentHelper->__('Card Verification Number'); ?>" class="required-entry input-text validate-cc-cvn" id="<?php echo $code; ?>_cc_cid" name="payment[cc_cid]" style="width:5em;" value="<?php echo $this->getInfoData('cc_cid'); ?>"/>
        </div>
    </li>
    <?php endif; ?>
</ul>
